name: DumprX
 
on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "Direct Link of the ROM/Firmware to Dump"
        required: true
      EXTRA_CMD:
        description: "Any Extra Command to Run Before Dump"
        required: false

defaults:
  run:
    shell: bash

env:
  # ROM
  ROM_URL: ${{ github.event.inputs.ROM_URL }}

  # Gitlab
  PUSH_TO_GITLAB: true

  # Extra Command
  EXTRA_CMD: ${{ github.event.inputs.EXTRA_CMD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Maximize build space
         uses: easimon/maximize-build-space@master
         with:
              root-reserve-mb: 512
              temp-reserve-mb: 100
              swap-size-mb: 1024
              remove-dotnet: 'true'
              remove-android: 'true'
              remove-haskell: 'true'
              remove-codeql: 'true'
              remove-docker-images: 'true'
          
       - name: Checkouts
         uses: actions/checkout@v4

       - name: Clone Our Firmware Dumper
         run: |
              git clone https://github.com/Vuong-Android-Dumps/DumprX-Script.git DumprX

       - name: Setup Config envs
         working-directory: DumprX
         run: |  
              mkdir -p ~/.ssh
              ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
              ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
              echo "${{ secrets.PRIV_SSH_KEY }}" > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              echo "${{ secrets.GITLAB_TOKEN }}" > .gitlab_token
              echo "Van-Firmware-Dumps" > .gitlab_group
              echo "gitlab.com" > .gitlab_instance
              echo "${{ secrets.TG_TOKEN }}" > .tg_token
              echo "@VanFirmwareDumps" > .tg_chat

       - name: Setup DumprX's Environment
         working-directory: DumprX
         run: |
              git config --global user.name "VanVuong41429"
              git config --global user.email "vanvuong41429@gmail.com"
              git config --global lfs.concurrenttransfers 1
              git config --global lfs.tlstimeout 300
              git config --global lfs.activitytimeout 300
              git config --global lfs.dialtimeout 300
              sudo bash setup.sh

       - name: Run the Extra Command
         working-directory: DumprX
         run: |
              $EXTRA_CMD

       - name: Start Dumping
         working-directory: DumprX
         run: |
              ./dumper.sh "$ROM_URL"
